name: CI

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2.1.0
    - name: Setup Node.js environment
      run: |
          npm install --global yo gulp-cli generator-webapp
          yarn
          gulp

